name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: build dir
      run: mkdir build
    - name: configure 
      run: cmake ..
      working-directory: ./build
    - name: build & run tests
      run: make tests
      working-directory: ./build
