name: build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

defaults:
  run:
    shell: bash

jobs:
  Linux:
    runs-on: ubuntu-latest 
    steps:
    - uses: actions/checkout@v2
    - name: build dir
      run: mkdir build
    - name: configure 
      run: cmake -DCMAKE_BUILD_TYPE=Release ..
      working-directory: ./build
    - name: build
      run: cmake --build .
      working-directory: ./build
    - name: run tests
      run: ./tests 
      working-directory: ./build

  MacOS:
    runs-on: macos-latest 
    steps:
    - uses: actions/checkout@v2
    - name: build dir
      run: mkdir build
    - name: configure 
      run: cmake -DCMAKE_BUILD_TYPE=Release ..
      working-directory: ./build
    - name: build
      run: cmake --build .
      working-directory: ./build
    - name: run tests
      run: ./tests 
      working-directory: ./build
  
  Windows:
    runs-on: windows-latest 
    steps:
    - uses: actions/checkout@v2
    - name: build dir
      run: mkdir build
    - name: configure 
      run: cmake -DCMAKE_BUILD_TYPE=Release ..
      working-directory: ./build
    - name: build
      run: cmake --build . --config Release
      working-directory: ./build
    - name: run tests
      run: ctest -V -C Release
      working-directory: ./build
